name: CHARLES HOFFMAN PHOTOGRAPHY
favicon: null
layout_spectrum: 0.7714827514719218
typography_spectrum: 0.3151541955303401
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.764136569108814
  lightness: 0.02875669184140861
  saturation: 0.5172011130489409
  rhythmicContrast: 0.742502408567816
purpose: []
