name: CHARLES HOFFMAN PHOTOGRAPHY
favicon: null
layout_spectrum: 1
typography_spectrum: 0.81923
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120500'
    - '#f3ebec'
    - '#847f7f'
    - '#64595a'
    - '#bfb7b8'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
